---
'$schema': https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2
final_space: true
console_title_template: '{{ .Shell }} in {{ .Folder }}'
var: 
    root_prompt: '#'
    user_prompt: '$'
blocks:
    - type: prompt
      alignment: left
      segments:
          - type: session
            style: diamond
            foreground: p:black
            background: p:yellow
            leading_diamond: ''
            trailing_diamond: ''
            template: ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
          - type: path
            style: powerline
            powerline_symbol: ''
            foreground: p:white
            background: p:orange
            template: '  {{ path .Path .Location }} '
            properties:
                style: folder
          - type: git
            style: powerline
            powerline_symbol: ''
            foreground: p:black
            foreground_templates:
                - '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}'
                - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}'
                - '{{ if gt .Ahead 0 }}p:white{{ end }}'
            background: p:green
            background_templates:
                - '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}'
                - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}'
                - '{{ if gt .Ahead 0 }}#49416D{{ end }}'
                - '{{ if gt .Behind 0 }}#7A306C{{ end }}'
            template: ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{
                .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed
                }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String
                }}{{ end }} '
            properties:
                branch_max_length: 25
                fetch_status: true
                fetch_upstream_icon: true
          - type: root
            style: powerline
            powerline_symbol: ''
            foreground: p:white
            background: p:yellow
            template: '  '
          - type: exit
            style: diamond
            foreground: p:white
            background: p:blue
            background_templates:
                - '{{ if gt .Code 0 }}p:red{{ end }}'
            leading_diamond: '<transparent,background></>'
            trailing_diamond: ''
            template: ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
            properties:
                always_enabled: true
    - type: prompt
      alignment: right
      style: diamond
      leading_diamond: ''
      trailing_diamond: ''
      foreground: p:white
      background: p:orange
      segments:
          - type: node
            style: plain
            foreground: p:green
            background: transparent
            template: ' '
            properties:
                display_mode: files
                fetch_package_manager: false
                home_enabled: false
          - type: go
            style: plain
            foreground: p:blue
            background: transparent
            template: ' '
            properties:
                fetch_version: false
          - type: python
            style: plain
            foreground: p:yellow
            background: transparent
            template: '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
            # template: ' {{ .Full }} {{ if .Venv }}{{ .Venv }}{{ end }}'
            properties:
                display_mode: files
                fetch_version: false
                fetch_virtual_env: true
                display_default: true
                home_enabled: true
                always_enabled: true
          - type: shell
            style: powerline
            foreground: p:white
            background: transparent
            leading_diamond: ''
            trailing_diamond: ''
            template: '[<p:blue><b>{{ .Name }}</b></>|'
          - type: time
            style: plain
            newline: true
            # foreground: p:white
            # background: transparent
            template: '<p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>]'
    # - type: prompt
    #   newline: true
    #   alignment: left
    #   segments:
    #     - type: text
    #       style: diamond
    #       foreground: p:white
    #       background: p:orange
    #       leading_diamond: ''
    # - type: prompt
    #   alignment: left
    #   newline: true
    #   segments:
    #     - foreground: "#cd5e42"
    #       style: plain
    #       template: " "
    #       type: root
    #     - foreground: "#CD4277"
    #       style: plain
    #       template: "# "
    #       type: text
    - type: prompt
      alignment: left
      newline: true
      segments:
      - foreground: "#21c7c7"
        foreground_templates:
            - "{{ if gt .Code 0 }}#ef5350{{ end }}"
        style: plain
        template: "{{ if .Root }} # {{ else }} $ {{ end }}"
        type: exit
        properties:
            always_enabled: true
    #   - foreground: "#e0f8ff"
    #     foreground_templates:
    #         - "{{ if gt .Code 0 }}#ef5350{{ end }}"
    #     properties:
    #         always_enabled: true
    #     style: plain
    #     template: " "
    #     type: exit
    # - type: prompt
    #   alignment: left
    #   newline: true
    #   segments:
    #   - foreground: "#21c7c7"
    #     style: plain
    #     template: ╰─
    #     type: text
    #   - foreground: "#e0f8ff"
    #     foreground_templates:
    #         - "{{ if gt .Code 0 }}#ef5350{{ end }}"
    #     properties:
    #         always_enabled: true
    #     style: plain
    #     template: " "
    #     type: exit
  


tooltips:
    - type: aws
      tips:
          - aws
      style: diamond
      foreground: p:white
      background: p:orange
      leading_diamond: ''
      trailing_diamond: ''
      template: '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
      properties:
          display_default: true
    - type: az
      tips:
          - az
      style: diamond
      foreground: p:white
      background: p:blue
      leading_diamond: ''
      trailing_diamond: ''
      template: ' ﴃ {{ .Name }} '
      properties:
          display_default: true
transient_prompt:
    foreground: p:black
    background: transparent
    template: '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
secondary_prompt:
    foreground: p:black
    background: transparent
    template: '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
palette:
    black: '#262B44'
    blue: '#4B95E9'
    green: '#59C9A5'
    orange: '#F07623'
    red: '#D81E5B'
    white: '#E0DEF4'
    yellow: '#F3AE35'
